FROM node:20-slim AS build

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

COPY schema.graphql /app/schema.graphql
RUN sed -i "s|'../back/schemas/unifesspa/schema.graphql'|'./schema.graphql'|" /app/relay.config.js

RUN pnpm relay
RUN pnpm build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
